name: workflows-demo
recipe: drupal9
config:
  webroot: web
services:
  appserver:
    build:
      - composer install
tooling:
  drush:
    service: appserver
    env:
      DRUSH_OPTIONS_URI: "https://workflows-demo.lndo.site"
  drupal:
    service: appserver
    cmd: /app/vendor/bin/drupal