name: workflows-demo
recipe: drupal9
config:
  webroot: web
services:
  appserver:
    build:
      - composer install
tooling:
  drush:
    service: appserver
    cmd: "drush --root=/app/web --uri=https://workflows-demo.lndo.site/"
