<?php

/**
 * @file
 * Contains app_dashboard.module.
 */

 /**
 * Implements hook_theme().
 */
function app_dashboard_theme($existing, $type, $theme, $path) {
  return [
    'app_meta' => [
      'variables' => [
        'isOvernight' => NULL,
        'canAttendTraining' => NULL,
        'resumeUrl' => NULL,
        'appUrl' => NULL,
      ],
    ],
    'app_dashboard' => [
      'variables' => [
        'submitted' => 0,
        'interview' => 0,
        'offered' => 0,
        'rejected' => 0,
        'prospect' => 0,
        'hired' => 0,
      ],
    ],
  ];
}
